---
abstract: 'Build, test and do with all perls'
author:
  - 'Reini Urban <rurban@cpanel.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-perlall
no_index:
  directory:
    - t
    - inc
recommends:
  File::Slurp: 9999.13
requires:
  App::Rad: 1.04
  Cwd: 3.30
  Devel::PatchPerl: 0.46
  Devel::Platform::Info: 0
  File::Basename: 2.74
  File::Path: 1.08
  Getopt::Long: 2.36
  IO::Scalar: 0
  IPC::Cmd: 0.46
  IPC::Open3: 0
  Pod::Usage: 1.33
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rurban/App-perlall.git
version: 0.13
